export type HistoryQuestion = {
  id: string;
  prompt: string;
  year: number;
  min: number;
  max: number;
  difficulty: 'core' | 'survey' | 'specialist';
  detail: string;
  source: string;
  sourceUrl: string;
  verifiedAt: string;
};

export const historyQuestionTarget = 1000;
export const dailyHistoryQuestionCount = 10;

export const historyQuestions: HistoryQuestion[] = [
  { id: 'djoser-step-pyramid', prompt: 'Around when was Djoser’s Step Pyramid built?', year: -2780, min: -3200, max: -2300, difficulty: 'survey', detail: 'The Smithsonian dates the project to around 2780 BCE and identifies Imhotep as its architect. The exact chronology of Egypt’s Third Dynasty remains approximate.', source: 'Smithsonian Institution — The Egyptian Pyramid', sourceUrl: 'https://www.si.edu/spotlight/ancient-egypt/pyramid', verifiedAt: '2026-08-31' },
  { id: 'code-of-hammurabi', prompt: 'Around when was Hammurabi’s law code carved?', year: -1750, min: -2200, max: -1300, difficulty: 'survey', detail: 'The Louvre dates the surviving stela to Hammurabi’s reign, 1792–1750 BCE. This game uses 1750 BCE as a memorable approximate anchor, not a precise day.', source: 'Musée du Louvre — Code of Hammurabi', sourceUrl: 'https://collections.louvre.fr/en/ark:/53355/cl010174436', verifiedAt: '2026-08-31' },
  { id: 'olmec-florescence', prompt: 'Around when did the Olmec cultural florescence begin?', year: -1200, min: -1600, max: -700, difficulty: 'survey', detail: 'The Met dates the major Olmec cultural and artistic florescence on Mexico’s Gulf Coast to roughly 1200–400 BCE. “Olmec” groups were not a single unified empire.', source: 'Metropolitan Museum of Art — Olmec Art', sourceUrl: 'https://www.metmuseum.org/es/essays/olmec-art', verifiedAt: '2026-08-31' },
  { id: 'achaemenid-empire', prompt: 'Around when did the Achaemenid Persian Empire begin?', year: -550, min: -800, max: -300, difficulty: 'core', detail: 'The Achaemenid Empire is conventionally dated from about 550 BCE, when Cyrus II overthrew the Median king and began a rapid imperial expansion.', source: 'Metropolitan Museum of Art — Achaemenid Persian Empire', sourceUrl: 'https://www.metmuseum.org/ja/essays/the-achaemenid-persian-empire-550-330-b-c', verifiedAt: '2026-08-31' },
  { id: 'mauryan-empire', prompt: 'Around when did the Mauryan Empire begin?', year: -321, min: -550, max: -100, difficulty: 'survey', detail: 'The Mauryan dynasty emerged around 321 BCE and built the first empire to unite most of the Indian subcontinent. Its boundaries changed over time.', source: 'Metropolitan Museum of Art — The Year One', sourceUrl: 'https://resources.metmuseum.org/resources/metpublications/pdf/The_Year_One_Art_of_the_Ancient_World_East_and_West.pdf', verifiedAt: '2026-08-31' },
  { id: 'teotihuacan-established', prompt: 'Around when was Teotihuacan established?', year: -150, min: -400, max: 100, difficulty: 'specialist', detail: 'The Met’s chronology places Teotihuacan’s establishment around 150 BCE. The settlement expanded over generations rather than appearing as a finished city in one year.', source: 'Metropolitan Museum of Art — Mexico, 1000 BCE–1 CE', sourceUrl: 'https://82nd-and-fifth.metmuseum.org/toah/ht/04/cam.html', verifiedAt: '2026-08-31' },
  { id: 'teotihuacan-city-grid', prompt: 'Around when was Teotihuacan’s city grid established?', year: 50, min: -150, max: 300, difficulty: 'specialist', detail: 'The Met dates establishment of Teotihuacan’s grid and early monumental construction along the Street of the Dead to around 50 CE.', source: 'Metropolitan Museum of Art — Mexico, 1–500 CE', sourceUrl: 'https://82nd-and-fifth.metmuseum.org/toah/ht/05/cam.html', verifiedAt: '2026-08-31' },
  { id: 'classic-maya-city-states', prompt: 'Around when did Classic Maya dynastic city-states emerge?', year: 250, min: 1, max: 600, difficulty: 'survey', detail: 'The conventional Classic Maya period begins around 250 CE, when dynastic city-states and their characteristic monuments became prominent. Period boundaries are scholarly tools.', source: 'Metropolitan Museum of Art — Maya Area, 1–500 CE', sourceUrl: 'https://82nd-and-fifth.metmuseum.org/toah/ht/05/caa.html', verifiedAt: '2026-08-31' },
  { id: 'aksumite-coinage', prompt: 'Around when did the kingdom of Aksum begin issuing coins?', year: 270, min: 1, max: 600, difficulty: 'specialist', detail: 'Aksum began minting its own coinage around the late third century CE. The exact opening date is approximate, so the game uses 270 CE as a rough anchor.', source: 'Metropolitan Museum of Art — Foundations of Aksumite Civilization', sourceUrl: 'https://www.metmuseum.org/ja/essays/foundations-of-aksumite-civilization-and-its-christian-legacy-1st-7th-century', verifiedAt: '2026-08-31' },
  { id: 'gupta-dynasty', prompt: 'Around when did the Gupta dynasty begin?', year: 320, min: 100, max: 600, difficulty: 'survey', detail: 'The Gupta era is conventionally dated from around 320 CE. Its political reach and the “golden age” label both require regional and cultural qualification.', source: 'Smarthistory — The Gupta Period', sourceUrl: 'https://smarthistory.org/gupta-period/', verifiedAt: '2026-08-31' },
  { id: 'teotihuacan-tikal', prompt: 'When did a Teotihuacan-linked force arrive at Tikal?', year: 378, min: 150, max: 600, difficulty: 'specialist', detail: 'Maya inscriptions record the arrival of a figure linked to Teotihuacan at Tikal in 378 CE, followed by a new ruler with strong central Mexican ties.', source: 'Metropolitan Museum of Art — Maya Area, 1–500 CE', sourceUrl: 'https://82nd-and-fifth.metmuseum.org/toah/ht/05/caa.html', verifiedAt: '2026-08-31' },
  { id: 'palenque-dynasty', prompt: 'When did Palenque’s recorded dynasty begin?', year: 431, min: 200, max: 700, difficulty: 'specialist', detail: 'Palenque’s inscriptions date the accession of its first recorded dynastic ruler, K’uk’ Balam I, to 431 CE. Earlier settlement at the site is not ruled out.', source: 'Metropolitan Museum of Art — Maya Area, 1–500 CE', sourceUrl: 'https://82nd-and-fifth.metmuseum.org/toah/ht/05/caa.html', verifiedAt: '2026-08-31' },
  { id: 'olympic-chronology', prompt: 'When does the reliable ancient Olympic chronology begin?', year: -776, min: -1100, max: -500, difficulty: 'specialist', detail: 'The conventional reliable list begins with the victor Koroibos in 776 BCE. Games and legends existed earlier, so this is not a claim that Olympic competition began that year.', source: 'Journal of Olympic History — Ancient Olympic Apocrypha', sourceUrl: 'https://library.olympics.com/digitalCollection/DigitalCollectionAttachmentDownloadHandler.ashx?documentId=2435425&parentDocumentId=2435424&skipCopyright=true&skipWatermark=true', verifiedAt: '2026-08-31' },
  { id: 'battle-of-marathon', prompt: 'When was the Battle of Marathon?', year: -490, min: -700, max: -300, difficulty: 'core', detail: 'Athenians and Plataeans defeated a Persian invasion force at Marathon in 490 BCE during the Greco-Persian Wars.', source: 'Encyclopaedia Britannica — Battle of Marathon', sourceUrl: 'https://www.britannica.com/event/Battle-of-Marathon', verifiedAt: '2026-08-31' },
  { id: 'alexander-death', prompt: 'When did Alexander the Great die?', year: -323, min: -500, max: -100, difficulty: 'core', detail: 'Alexander died unexpectedly in Babylon in June 323 BCE. His generals then fought over and divided the empire.', source: 'Metropolitan Museum of Art — The Hellenistic Age', sourceUrl: 'https://www.metmuseum.org/essays/art-of-the-hellenistic-age-and-the-hellenistic-tradition', verifiedAt: '2026-08-31' },
  { id: 'qin-unification', prompt: 'When did Qin unify China?', year: -221, min: -450, max: -50, difficulty: 'survey', detail: 'Ying Zheng conquered the remaining rival states and proclaimed himself First Emperor in 221 BCE. The Qin dynasty itself was short-lived.', source: 'Metropolitan Museum of Art — Age of Empires', sourceUrl: 'https://www.metmuseum.org/exhibitions/listings/2017/age-of-empires/exhibition-galleries', verifiedAt: '2026-08-31' },
  { id: 'augustus-title', prompt: 'When did Octavian receive the title Augustus?', year: -27, min: -150, max: 100, difficulty: 'survey', detail: 'The Roman Senate awarded Octavian the title Augustus in 27 BCE, the conventional beginning of the Roman imperial principate.', source: 'Metropolitan Museum of Art — The Roman Empire', sourceUrl: 'https://www.metmuseum.org/essays/the-roman-empire-27-b-c-393-a-d', verifiedAt: '2026-08-31' },
  { id: 'vesuvius-pompeii', prompt: 'When did Vesuvius bury Pompeii and Herculaneum?', year: 79, min: -100, max: 300, difficulty: 'core', detail: 'Mount Vesuvius erupted in 79 CE, burying Pompeii, Herculaneum, and nearby settlements and preserving an exceptional record of Roman life.', source: 'Metropolitan Museum of Art — Roman Art', sourceUrl: 'https://www.metmuseum.org/met-publications/roman-art-a-resource-for-educators', verifiedAt: '2026-08-31' },
  { id: 'constantinople-capital', prompt: 'When did Constantine establish Constantinople as New Rome?', year: 330, min: 150, max: 550, difficulty: 'survey', detail: 'Constantine dedicated Constantinople in 330 CE and shifted the imperial center eastward. Rome remained central to the western church.', source: 'Metropolitan Museum of Art — Italian Peninsula, 1–500 CE', sourceUrl: 'https://www.metmuseum.org/toah/ht/05/eust.html', verifiedAt: '2026-08-31' },
  { id: 'western-rome-end', prompt: 'When was the last western Roman emperor deposed?', year: 476, min: 250, max: 700, difficulty: 'core', detail: 'Odovacer deposed Romulus Augustulus in 476 CE, the conventional endpoint of the Western Roman Empire. The Eastern Roman Empire continued for centuries.', source: 'Metropolitan Museum of Art — The Roman Empire', sourceUrl: 'https://www.metmuseum.org/essays/the-roman-empire-27-b-c-393-a-d', verifiedAt: '2026-08-31' },
  { id: 'tang-dynasty', prompt: 'When did the Tang dynasty begin in China?', year: 618, min: 450, max: 850, difficulty: 'survey', detail: 'Li Yuan founded the Tang dynasty in 618 CE. Tang rule lasted, with an interruption, until 907 and presided over a major era of trade and cultural exchange.', source: 'Metropolitan Museum of Art — Central and North Asia, 500–1000', sourceUrl: 'https://82nd-and-fifth.metmuseum.org/toah/ht/06/nc.html', verifiedAt: '2026-08-31' },
  { id: 'hijra', prompt: 'When did Muhammad and his followers migrate to Medina?', year: 622, min: 450, max: 850, difficulty: 'core', detail: 'The Hijra from Mecca to Medina occurred in 622 CE. It marks the starting point of the Islamic calendar, not the beginning of Muhammad’s prophetic career.', source: 'Metropolitan Museum of Art — The Birth of Islam', sourceUrl: 'https://www.metmuseum.org/essays/the-birth-of-islam', verifiedAt: '2026-08-31' },
  { id: 'baghdad-founded', prompt: 'When did the Abbasids found Baghdad?', year: 762, min: 550, max: 1000, difficulty: 'survey', detail: 'The Abbasid caliph al-Mansur founded Baghdad as his new capital in 762 CE. The city became a major political, commercial, and intellectual center.', source: 'Metropolitan Museum of Art — Central and North Asia, 500–1000', sourceUrl: 'https://82nd-and-fifth.metmuseum.org/toah/ht/06/nc.html', verifiedAt: '2026-08-31' },
  { id: 'charlemagne-emperor', prompt: 'When was Charlemagne crowned emperor in Rome?', year: 800, min: 600, max: 1050, difficulty: 'core', detail: 'Pope Leo III crowned Charlemagne emperor in Rome on Christmas Day in 800 CE. The title shaped later claims to imperial authority in western Europe.', source: 'Metropolitan Museum of Art — Carolingian Art', sourceUrl: 'https://www.metmuseum.org/essays/carolingian-art', verifiedAt: '2026-08-31' },
  { id: 'norman-conquest', prompt: 'When did the Norman Conquest of England begin?', year: 1066, min: 850, max: 1250, difficulty: 'core', detail: 'William of Normandy invaded England and defeated Harold at Hastings in 1066. Conquest and consolidation continued after the battle.', source: 'UK Parliament — The Palace and the Normans', sourceUrl: 'https://www.parliament.uk/about/living-heritage/building/palace/estatehistory/the-middle-ages/palace-normans/', verifiedAt: '2026-08-31' },
  { id: 'first-crusade', prompt: 'When did Pope Urban II call the First Crusade?', year: 1095, min: 850, max: 1300, difficulty: 'survey', detail: 'Urban II called for an armed pilgrimage at the Council of Clermont in 1095. Crusading armies reached and captured Jerusalem in 1099.', source: 'Metropolitan Museum of Art — The Crusades', sourceUrl: 'https://www.metmuseum.org/toah/hd/crus/hd_crus.htm', verifiedAt: '2026-08-31' },
  { id: 'genghis-khan-proclaimed', prompt: 'When was Temüjin proclaimed Genghis Khan?', year: 1206, min: 950, max: 1400, difficulty: 'survey', detail: 'A great assembly recognized Temüjin as Genghis Khan in 1206, conventionally marking the foundation of the Mongol Empire.', source: 'Metropolitan Museum of Art — The Legacy of Genghis Khan', sourceUrl: 'https://www.metmuseum.org/essays/the-legacy-of-genghis-khan', verifiedAt: '2026-08-31' },
  { id: 'mali-empire-rise', prompt: 'Around when did the Mali Empire emerge?', year: 1235, min: 950, max: 1500, difficulty: 'specialist', detail: 'Mali’s rise is conventionally associated with Sundiata’s victory around 1235. The date is approximate and partly reconstructed from oral traditions.', source: 'Metropolitan Museum of Art — Empires of the Western Sudan', sourceUrl: 'https://www.metmuseum.org/essays/the-empires-of-the-western-sudan', verifiedAt: '2026-08-31' },
  { id: 'black-death-europe', prompt: 'When did the Black Death reach Europe?', year: 1347, min: 1150, max: 1550, difficulty: 'core', detail: 'The pandemic reached Mediterranean Europe in 1347 and spread widely through 1351. Outbreaks and demographic effects varied across regions.', source: 'Metropolitan Museum of Art — The Art of Renaissance Europe', sourceUrl: 'https://www.metmuseum.org/-/media/files/learn/for-educators/publications-for-educators/renaissance.pdf', verifiedAt: '2026-08-31' },
  { id: 'fall-of-constantinople', prompt: 'When did the Ottomans capture Constantinople?', year: 1453, min: 1250, max: 1650, difficulty: 'core', detail: 'Mehmed II’s Ottoman army captured Constantinople in May 1453, ending the Byzantine Empire. Trebizond remained independent until 1461.', source: 'Metropolitan Museum of Art — The Art of Renaissance Europe', sourceUrl: 'https://www.metmuseum.org/-/media/files/learn/for-educators/publications-for-educators/renaissance.pdf', verifiedAt: '2026-08-31' },
  { id: 'magna-carta', prompt: 'When was Magna Carta first issued?', year: 1215, min: 1000, max: 1500, difficulty: 'core', detail: 'King John authorized the first Magna Carta at Runnymede in June 1215. Later reissues changed its text and legacy.', source: 'UK Parliament — Magna Carta', sourceUrl: 'https://www.parliament.uk/about/living-heritage/evolutionofparliament/originsofparliament/birthofparliament/overview/magnacarta/', verifiedAt: '2026-08-31' },
  { id: 'ming-dynasty', prompt: 'When did Zhu Yuanzhang establish the Ming dynasty?', year: 1368, min: 1150, max: 1550, difficulty: 'survey', detail: 'Zhu Yuanzhang emerged victorious in 1368, expelled the Yuan court, and ruled as the Hongwu emperor.', source: 'Metropolitan Museum of Art — The Yuan Revolution', sourceUrl: 'https://www.metmuseum.org/exhibitions/listings/2010/yuan-revolution', verifiedAt: '2026-08-31' },
  { id: 'gutenberg-printing', prompt: 'Around when did Gutenberg-era movable-type printing begin in Europe?', year: 1450, min: 1250, max: 1650, difficulty: 'core', detail: 'The date is approximate: historians place the beginning of European typography around 1450, before the Gutenberg Bible was completed.', source: 'Library of Congress — Gutenberg resources', sourceUrl: 'https://guides.loc.gov/gutenberg/resources', verifiedAt: '2026-08-31' },
  { id: 'columbus-caribbean', prompt: 'When did Columbus first reach the Caribbean?', year: 1492, min: 1300, max: 1700, difficulty: 'core', detail: 'Columbus reached the Bahamian island Guanahaní on 12 October 1492, beginning a new phase of European conquest and colonization.', source: 'Library of Congress — Columbus and the Taíno', sourceUrl: 'https://www.loc.gov/exhibits/exploring-the-early-americas/columbus-and-the-taino.html', verifiedAt: '2026-08-31' },
  { id: 'qing-dynasty', prompt: 'When did the Manchus establish Qing rule in China?', year: 1644, min: 1450, max: 1800, difficulty: 'survey', detail: 'The Manchus entered Beijing and established Qing rule in 1644; conquest and consolidation continued for decades.', source: 'Metropolitan Museum of Art — The Qing Dynasty', sourceUrl: 'https://www.metmuseum.org/essays/the-qing-dynasty-1644-1911-painting', verifiedAt: '2026-08-31' },
  { id: 'spinning-jenny', prompt: 'When did James Hargreaves invent the spinning jenny?', year: 1764, min: 1600, max: 1900, difficulty: 'survey', detail: 'Hargreaves is generally credited with inventing the multi-spindle spinning jenny around 1764; he patented a later version in 1770.', source: 'Encyclopaedia Britannica — Spinning jenny', sourceUrl: 'https://www.britannica.com/technology/spinning-jenny', verifiedAt: '2026-08-31' },
  { id: 'watt-patent', prompt: 'When was Watt’s separate-condenser patent granted?', year: 1769, min: 1600, max: 1900, difficulty: 'survey', detail: 'Watt conceived the separate condenser earlier, but this question asks for the patent granted on 5 January 1769.', source: 'Science Museum — James Watt and the separate condenser', sourceUrl: 'https://blog.sciencemuseum.org.uk/james-watt-and-the-separate-condenser/', verifiedAt: '2026-08-31' },
  { id: 'french-revolution', prompt: 'When did the French Revolution begin?', year: 1789, min: 1650, max: 1950, difficulty: 'core', detail: 'This uses 1789, the year of the Estates-General, the National Assembly, and the storming of the Bastille, as the conventional start.', source: 'U.S. National Archives — Onset of the French Revolution', sourceUrl: 'https://www.archives.gov/exhibits/eyewitness/html.php?section=1', verifiedAt: '2026-08-31' },
  { id: 'haitian-independence', prompt: 'When did Haiti declare independence from France?', year: 1804, min: 1650, max: 1950, difficulty: 'survey', detail: 'Haitian generals signed the declaration on 1 January 1804 after a thirteen-year revolution against slavery and colonial rule.', source: 'Library of Congress — Ayiti Reimagined', sourceUrl: 'https://guides.loc.gov/haiti-reimagined', verifiedAt: '2026-08-31' },
  { id: 'telegraph', prompt: 'When was a practical electric telegraph first demonstrated in Britain?', year: 1837, min: 1700, max: 2000, difficulty: 'specialist', detail: 'Cooke and Wheatstone demonstrated their five-needle electric telegraph to railway directors in 1837.', source: 'Science Museum — Cooke and Wheatstone telegraph', sourceUrl: 'https://blog.sciencemuseum.org.uk/revealing-the-real-cooke-and-wheatstone-telegraph-dial/', verifiedAt: '2026-08-31' },
  { id: 'meiji-restoration', prompt: 'When did the Meiji Restoration change Japan’s regime?', year: 1868, min: 1700, max: 2000, difficulty: 'survey', detail: 'Imperial rule was proclaimed in January 1868, beginning the new Meiji government and a far-reaching transformation of Japan.', source: 'National Diet Library of Japan — Meiji government', sourceUrl: 'https://www.ndl.go.jp/portrait/e/pickup/012/', verifiedAt: '2026-08-31' },
  { id: 'indian-independence', prompt: 'When did British rule end in India?', year: 1947, min: 1800, max: 2020, difficulty: 'core', detail: 'British India was partitioned into India and Pakistan in August 1947; independence and partition unfolded together.', source: 'UK National Archives — Indian Independence', sourceUrl: 'https://www.nationalarchives.gov.uk/education/resources/indian-independence/', verifiedAt: '2026-08-31' },
  { id: 'berlin-wall-fall', prompt: 'When did the Berlin Wall fall?', year: 1989, min: 1900, max: 2020, difficulty: 'core', detail: 'East Germany opened the border on 9 November 1989. Formal German reunification followed in October 1990.', source: 'German Bundestag — 1989–1990', sourceUrl: 'https://www.bundestag.de/resource/blob/480634/exhibition_dome.pdf', verifiedAt: '2026-08-31' },
  { id: 'stockton-darlington-railway', prompt: 'When did the first steam-hauled passenger train run on a public railway?', year: 1825, min: 1650, max: 2000, difficulty: 'specialist', detail: 'On 27 September 1825, Locomotion No. 1 hauled a passenger train on the Stockton and Darlington Railway, the first steam-hauled passenger public railway.', source: 'National Railway Museum — Shildon and Locomotion No. 1', sourceUrl: 'https://blog.railwaymuseum.org.uk/shildon-the-cradle-of-the-railways-and-locomotion-no-1/', verifiedAt: '2026-08-31' },
  { id: 'mendeleev-periodic-table', prompt: 'When did Mendeleev devise his periodic table?', year: 1869, min: 1700, max: 2000, difficulty: 'survey', detail: 'Dmitri Mendeleev devised his periodic system in February 1869 while arranging the known elements by atomic weight and recurring chemical properties.', source: 'Royal Society of Chemistry — Development of the periodic table', sourceUrl: 'https://periodic-table.rsc.org/about', verifiedAt: '2026-08-31' },
  { id: 'wright-first-flight', prompt: 'When did the Wright brothers make the first successful powered airplane flight?', year: 1903, min: 1750, max: 2020, difficulty: 'core', detail: 'Orville Wright piloted the first of four successful powered flights at Kitty Hawk on 17 December 1903; the opening flight lasted twelve seconds.', source: 'Smithsonian National Air and Space Museum — 1903 Wright Flyer', sourceUrl: 'https://airandspace.si.edu/collection-objects/1903-wright-flyer/nasm_A19610048000', verifiedAt: '2026-08-31' },
  { id: 'fleming-penicillin', prompt: 'When did Alexander Fleming discover penicillin?', year: 1928, min: 1800, max: 2020, difficulty: 'core', detail: 'Fleming observed in 1928 that a Penicillium mould inhibited bacterial growth. He published the finding in 1929; later teams made penicillin a practical drug.', source: 'Nobel Prize — Alexander Fleming questions and answers', sourceUrl: 'https://www.nobelprize.org/prizes/medicine/1945/fleming/questions-and-answers/', verifiedAt: '2026-08-31' },
  { id: 'dna-double-helix', prompt: 'When was the double-helix structure of DNA determined?', year: 1953, min: 1800, max: 2020, difficulty: 'core', detail: 'Watson and Crick determined the double-helix structure in 1953, building on essential experimental work by Rosalind Franklin, Maurice Wilkins, and others.', source: 'Nobel Prize — Exploring life’s smallest details', sourceUrl: 'https://www.nobelprize.org/stories/cells-nerves-genes/', verifiedAt: '2026-08-31' },
  { id: 'sputnik-1', prompt: 'When did the Soviet Union launch Sputnik 1?', year: 1957, min: 1850, max: 2020, difficulty: 'survey', detail: 'The Soviet Union launched Sputnik 1 on 4 October 1957. It was the first artificial satellite and marked the conventional opening of the Space Age.', source: 'NASA — Dawn of the Space Age', sourceUrl: 'https://www.nasa.gov/history/dawn-of-the-space-age/', verifiedAt: '2026-08-31' },
  { id: 'apollo-11-moon-landing', prompt: 'When did humans first land on the Moon?', year: 1969, min: 1850, max: 2020, difficulty: 'core', detail: 'Apollo 11 landed on 20 July 1969. Neil Armstrong and Buzz Aldrin walked on the lunar surface while Michael Collins remained in lunar orbit.', source: 'NASA — Apollo 11 Mission Overview', sourceUrl: 'https://www.nasa.gov/missions/apollo/apollo-11/apollo-11-mission-overview/', verifiedAt: '2026-08-31' },
  { id: 'smallpox-eradication', prompt: 'When did the World Health Assembly declare smallpox eradicated?', year: 1980, min: 1850, max: 2020, difficulty: 'survey', detail: 'The World Health Assembly officially declared smallpox eradicated in May 1980 after an international vaccination and surveillance campaign.', source: 'World Health Organization — History of smallpox vaccination', sourceUrl: 'https://www.who.int/news-room/spotlight/history-of-vaccination/history-of-smallpox-vaccination', verifiedAt: '2026-08-31' },
  { id: 'human-genome-project-complete', prompt: 'When was the Human Genome Project declared complete?', year: 2003, min: 1900, max: 2020, difficulty: 'survey', detail: 'The international consortium announced completion on 14 April 2003. Its sequence covered about 92% of the genome; a gapless sequence came later.', source: 'National Human Genome Research Institute — Human Genome Project Timeline', sourceUrl: 'https://www.genome.gov/human-genome-project/timeline', verifiedAt: '2026-08-31' },
  { id: 'crispr-cas9-genome-editing', prompt: 'When was CRISPR-Cas9 demonstrated as a programmable genome-editing tool?', year: 2012, min: 1900, max: 2020, difficulty: 'specialist', detail: 'Emmanuelle Charpentier and Jennifer Doudna reported programmable CRISPR-Cas9 genetic scissors in 2012, enabling targeted changes to DNA.', source: 'Nobel Prize — Chemistry 2020 press release', sourceUrl: 'https://www.nobelprize.org/prizes/chemistry/2020/press-release/', verifiedAt: '2026-08-31' },
  { id: 'jenner-smallpox-vaccination', prompt: 'When did Edward Jenner perform his famous smallpox vaccination experiment?', year: 1796, min: 1600, max: 1950, difficulty: 'core', detail: 'Jenner inoculated James Phipps with material from a cowpox lesion in May 1796, then tested whether it protected him from smallpox. Variolation traditions predated this experiment.', source: 'U.S. National Library of Medicine — Smallpox vaccination', sourceUrl: 'https://www.nlm.nih.gov/exhibition/smallpox/sp_vaccination.html', verifiedAt: '2026-08-31' },
  { id: 'ether-anesthesia-demonstration', prompt: 'When was ether anesthesia first demonstrated publicly in surgery?', year: 1846, min: 1700, max: 2000, difficulty: 'survey', detail: 'William T. G. Morton publicly demonstrated ether anesthesia during surgery at Massachusetts General Hospital on 16 October 1846. Earlier practitioners had used ether without this public demonstration.', source: 'Massachusetts General Hospital — 200 years of patient care', sourceUrl: 'https://www.massgeneral.org/news/press-release/massachusetts-general-hospital-marks-200-years-of-patient-care', verifiedAt: '2026-08-31' },
  { id: 'lister-antiseptic-surgery', prompt: 'When did Joseph Lister publish his antiseptic surgical method?', year: 1867, min: 1750, max: 2000, difficulty: 'survey', detail: 'Lister published a series of reports on carbolic-acid treatment of surgical wounds in 1867. The method evolved, and modern aseptic practice differs from his original technique.', source: 'PubMed Central — On the Antiseptic Principle in the Practice of Surgery', sourceUrl: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC2895849/', verifiedAt: '2026-08-31' },
  { id: 'roentgen-x-rays', prompt: 'When did Wilhelm Röntgen discover X-rays?', year: 1895, min: 1750, max: 2020, difficulty: 'core', detail: 'Röntgen observed the new radiation in November 1895 and submitted his first paper in December. Diagnostic applications spread rapidly during the following year.', source: 'PubMed — Early history of X-ray diagnosis', sourceUrl: 'https://pubmed.ncbi.nlm.nih.gov/8587931/', verifiedAt: '2026-08-31' },
  { id: 'insulin-discovery', prompt: 'When did the Toronto team begin the experiments that led to insulin therapy?', year: 1921, min: 1800, max: 2020, difficulty: 'survey', detail: 'Frederick Banting and Charles Best began their pancreatic-extract experiments in 1921 under John Macleod. James Collip later helped purify insulin for human treatment.', source: 'Nobel Prize — The discovery of insulin', sourceUrl: 'https://educationalgames.nobelprize.org/educational/medicine/insulin/discovery-insulin.html', verifiedAt: '2026-08-31' },
  { id: 'salk-polio-vaccine', prompt: 'When was the first effective Salk polio vaccine announced?', year: 1955, min: 1850, max: 2020, difficulty: 'core', detail: 'Results announced on 12 April 1955 showed that the inactivated vaccine developed by Jonas Salk and his team was effective. A manufacturing failure soon prompted stronger oversight.', source: 'CDC — 50th anniversary of the first effective polio vaccine', sourceUrl: 'https://www.cdc.gov/mmwr/preview/mmwrhtml/mm5413a5.htm', verifiedAt: '2026-08-31' },
  { id: 'first-human-heart-transplant', prompt: 'When was the first human-to-human heart transplant performed?', year: 1967, min: 1900, max: 2020, difficulty: 'core', detail: 'Christiaan Barnard and his team performed the operation in Cape Town on 3 December 1967. Recipient Louis Washkansky survived eighteen days before dying of pneumonia.', source: 'PubMed Central — First human heart transplant', sourceUrl: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4200566/', verifiedAt: '2026-08-31' },
  { id: 'first-ivf-birth', prompt: 'When was the first child conceived through IVF born?', year: 1978, min: 1900, max: 2020, difficulty: 'core', detail: 'Louise Brown was born on 25 July 1978 after IVF work by Robert Edwards, Patrick Steptoe, and Jean Purdy. The milestone established IVF as a viable clinical treatment.', source: 'Nobel Prize — Physiology or Medicine 2010 press release', sourceUrl: 'https://www.nobelprize.org/prizes/medicine/2010/press-release/', verifiedAt: '2026-08-31' },
  { id: 'hiv-isolated-identified', prompt: 'When was the virus now known as HIV first isolated and identified?', year: 1983, min: 1900, max: 2020, difficulty: 'survey', detail: 'A Pasteur Institute team reported a newly isolated retrovirus in 1983. Work by several groups in 1983–1984 established the virus now called HIV as the cause of AIDS.', source: 'NCBI Bookshelf — Acquired immune deficiency syndrome', sourceUrl: 'https://www.ncbi.nlm.nih.gov/books/NBK27126/', verifiedAt: '2026-08-31' },
  { id: 'first-covid-vaccine-doses', prompt: 'When were the first COVID-19 vaccine doses administered?', year: 2020, min: 1900, max: 2020, difficulty: 'core', detail: 'The first COVID-19 vaccine doses were administered in December 2020, less than a year after the first recognized cases. Some of the vaccines used mRNA technology.', source: 'World Health Organization — A brief history of vaccination', sourceUrl: 'https://www.who.int/news-room/spotlight/history-of-vaccination/a-brief-history-of-vaccination', verifiedAt: '2026-08-31' },
  { id: 'uruk-first-city', prompt: 'Around when had Uruk become the largest city in southern Mesopotamia?', year: -3200, min: -4000, max: -2500, difficulty: 'survey', detail: 'By around 3200 BCE, Uruk was the largest known settlement in southern Mesopotamia and a true city with monumental buildings. Urbanization developed over centuries.', source: 'Metropolitan Museum of Art — Uruk: The First City', sourceUrl: 'https://www.metmuseum.org/de/essays/uruk-the-first-city', verifiedAt: '2026-08-31' },
  { id: 'mature-harappan-cities', prompt: 'Around when did the mature urban phase of the Indus civilization begin?', year: -2600, min: -3300, max: -1800, difficulty: 'survey', detail: 'The mature Harappan urban phase is conventionally dated to about 2600–1900 BCE, when cities including Mohenjo-daro and Harappa flourished.', source: 'Metropolitan Museum of Art — South Asia, 8000–2000 BCE', sourceUrl: 'https://82nd-and-fifth.metmuseum.org/toah/ht/02/ssa.html', verifiedAt: '2026-08-31' },
  { id: 'shang-dynasty', prompt: 'Around when did the Shang dynasty begin?', year: -1600, min: -2200, max: -1000, difficulty: 'survey', detail: 'The archaeologically documented Shang dynasty is conventionally dated to about 1600–1046 BCE. Earlier dynastic traditions remain harder to verify archaeologically.', source: 'Metropolitan Museum of Art — Shang and Zhou Dynasties', sourceUrl: 'https://www.metmuseum.org/pt/essays/shang-and-zhou-dynasties-the-bronze-age-of-china', verifiedAt: '2026-08-31' },
  { id: 'chavin-culture', prompt: 'Around when did the Chavín culture begin in the Peruvian Andes?', year: -1500, min: -2200, max: -500, difficulty: 'specialist', detail: 'UNESCO dates the Chavín culture to roughly 1500–300 BCE. Its highland ceremonial center influenced a wide region, but the period boundaries remain approximate.', source: 'UNESCO World Heritage Centre — Chavín archaeological site', sourceUrl: 'https://whc.unesco.org/en/list/330', verifiedAt: '2026-08-31' },
  { id: 'zhou-conquest', prompt: 'Around when did the Zhou dynasty replace the Shang?', year: -1046, min: -1500, max: -600, difficulty: 'survey', detail: 'The Zhou conquest of the Shang is conventionally dated to 1046 BCE. The Western Zhou then exercised authority over much of central China.', source: 'Metropolitan Museum of Art — Shang and Zhou Dynasties', sourceUrl: 'https://www.metmuseum.org/pt/essays/shang-and-zhou-dynasties-the-bronze-age-of-china', verifiedAt: '2026-08-31' },
  { id: 'han-dynasty-begins', prompt: 'When did the Han dynasty begin?', year: -206, min: -500, max: 100, difficulty: 'core', detail: 'The Han dynasty established rule in 206 BCE after the collapse of the Qin and ensuing civil war. A brief interregnum later divided Western and Eastern Han periods.', source: 'Metropolitan Museum of Art — Age of Empires exhibition', sourceUrl: 'https://www.metmuseum.org/exhibitions/listings/2017/age-of-empires/exhibition-galleries', verifiedAt: '2026-08-31' },
  { id: 'yijing-srivijaya', prompt: 'When did the pilgrim Yijing first record arriving in Śrīvijaya?', year: 671, min: 400, max: 900, difficulty: 'specialist', detail: 'The Chinese Buddhist pilgrim Yijing described reaching Śrīvijaya in 671. Local Old Malay inscriptions from the 680s provide further evidence for the maritime power.', source: 'Metropolitan Museum of Art — Lost Kingdoms', sourceUrl: 'https://resources.metmuseum.org/resources/metpublications/pdf/Lost_Kingdoms_Hindu_Buddhist_Sculpture_of_Early_Southeast_Asia.pdf', verifiedAt: '2026-08-31' },
  { id: 'khmer-empire-802', prompt: 'When is the beginning of the Khmer Empire conventionally dated?', year: 802, min: 550, max: 1100, difficulty: 'survey', detail: 'An inscription associates Jayavarman II with a declaration of independence at Mahendraparvata in 802 CE, the conventional beginning of the Angkor-era Khmer Empire.', source: 'UNESCO World Heritage Centre — Phnom Kulen', sourceUrl: 'https://whc.unesco.org/fr/listesindicatives/6460/', verifiedAt: '2026-08-31' },
  { id: 'great-zimbabwe-building', prompt: 'Around when did major building begin at Great Zimbabwe?', year: 1100, min: 800, max: 1400, difficulty: 'survey', detail: 'UNESCO dates the surviving built complex broadly to 1100–1450 CE and describes an eleventh-century foundation. The city later became the center of a major Shona state.', source: 'UNESCO World Heritage Centre — Great Zimbabwe', sourceUrl: 'https://whc.unesco.org/en/list/364/', verifiedAt: '2026-08-31' },
  { id: 'tenochtitlan-founded', prompt: 'When was Tenochtitlan founded?', year: 1325, min: 1050, max: 1550, difficulty: 'core', detail: 'Tenochtitlan was founded in 1325 on an island in Lake Texcoco. It became the principal capital of the Mexica-led Triple Alliance in the fifteenth century.', source: 'Smithsonian Institution — The Death of Aztec Tenochtitlan', sourceUrl: 'https://www.si.edu/object/siris_sil_1055918', verifiedAt: '2026-08-31' },
  { id: 'lanse-aux-meadows', prompt: 'Around when did Norse voyagers establish L’Anse aux Meadows?', year: 1000, min: 700, max: 1300, difficulty: 'survey', detail: 'The Newfoundland site preserves an eleventh-century Norse settlement and the earliest confirmed European presence in North America. Indigenous peoples had lived in the region much earlier.', source: 'UNESCO World Heritage Centre — L’Anse aux Meadows', sourceUrl: 'https://whc.unesco.org/en/list/4/', verifiedAt: '2026-08-31' },
  { id: 'maori-settlement-aotearoa', prompt: 'Around when did Polynesian voyagers settle Aotearoa New Zealand?', year: 1275, min: 900, max: 1550, difficulty: 'survey', detail: 'Current evidence places the first lasting arrivals from East Polynesia between about 1250 and 1300 CE. The game uses 1275 as a midpoint, not an exact founding year.', source: 'Te Ara Encyclopedia of New Zealand — Māori arrival and settlement', sourceUrl: 'https://teara.govt.nz/en/history/page-1', verifiedAt: '2026-08-31' },
  { id: 'zheng-he-first-voyage', prompt: 'When did Zheng He depart on his first Indian Ocean voyage?', year: 1405, min: 1150, max: 1650, difficulty: 'survey', detail: 'The Yongle emperor sent Zheng He on the first of seven major maritime expeditions in 1405. The fleets connected Ming China with ports across the Indian Ocean.', source: 'Library of Congress — Voyages of Zheng He', sourceUrl: 'https://tile.loc.gov/storage-services/master/gdc/gdcebookspublic/20/20/71/93/50/2020719350/2020719350.pdf', verifiedAt: '2026-08-31' },
  { id: 'dias-cape-good-hope', prompt: 'When did Bartolomeu Dias round the Cape of Good Hope?', year: 1488, min: 1250, max: 1750, difficulty: 'survey', detail: 'Dias rounded southern Africa in 1488, demonstrating an Atlantic route into the Indian Ocean. His voyage preceded Vasco da Gama’s arrival in India by a decade.', source: 'Library of Congress — Portuguese India chronology', sourceUrl: 'https://tile.loc.gov/storage-services/service/gdc/gdclccn/a2/20/00/97/2/a22000972/a22000972.pdf', verifiedAt: '2026-08-31' },
  { id: 'vasco-da-gama-calicut', prompt: 'When did Vasco da Gama reach Calicut by sea?', year: 1498, min: 1250, max: 1750, difficulty: 'core', detail: 'Da Gama’s fleet reached Calicut on India’s Malabar Coast in May 1498 after sailing around Africa. Existing African and Indian Ocean pilots and trade networks made the crossing possible.', source: 'Library of Congress — Portuguese India chronology', sourceUrl: 'https://tile.loc.gov/storage-services/service/gdc/gdclccn/a2/20/00/97/2/a22000972/a22000972.pdf', verifiedAt: '2026-08-31' },
  { id: 'first-circumnavigation-complete', prompt: 'When did the first circumnavigation of Earth finish?', year: 1522, min: 1300, max: 1800, difficulty: 'core', detail: 'One ship from Magellan’s expedition returned to Spain in 1522 under Juan Sebastián Elcano, completing the first recorded circumnavigation. Magellan had died in 1521.', source: 'Library of Congress — Sailing the Early Seas with Portolan Charts', sourceUrl: 'https://blogs.loc.gov/maps/2019/09/sailing-the-early-seas-with-portolan-charts/', verifiedAt: '2026-08-31' },
  { id: 'manila-galleon-route', prompt: 'When did the Manila–Acapulco galleon trade begin?', year: 1565, min: 1350, max: 1850, difficulty: 'specialist', detail: 'Regular trans-Pacific galleon voyages began in 1565 and continued until 1815, carrying Asian goods eastward and American silver westward.', source: 'Smithsonian Libraries and Archives — The Manila Galleon', sourceUrl: 'https://www.si.edu/object/manila-galleon-william-lytle-schurz%3Asiris_sil_207127', verifiedAt: '2026-08-31' },
  { id: 'voc-founded', prompt: 'When was the Dutch East India Company founded?', year: 1602, min: 1400, max: 1900, difficulty: 'survey', detail: 'The Dutch Republic combined several competing trading companies into the Verenigde Oostindische Compagnie, or VOC, in 1602.', source: 'Rijksmuseum — East Indiamen off the coast', sourceUrl: 'https://www.rijksmuseum.nl/nl/collectie/object/Oost-Indievaarders-voor-de-kust--cb27a8dd65ec584d17acd8579e064ca4', verifiedAt: '2026-08-31' },
  { id: 'tasman-pacific-voyage', prompt: 'When did Abel Tasman reach Tasmania and New Zealand?', year: 1642, min: 1400, max: 1900, difficulty: 'specialist', detail: 'Tasman’s 1642–1643 VOC voyage charted parts of Tasmania and New Zealand before continuing through the Pacific to Tonga and Fiji.', source: 'Royal Museums Greenwich — Exploration and discovery guide', sourceUrl: 'https://www.rmg.co.uk/collections/research-guides/research-guide-q1-exploration-discovery', verifiedAt: '2026-08-31' },
  { id: 'cook-first-pacific-voyage', prompt: 'When did James Cook’s first Pacific voyage begin?', year: 1768, min: 1500, max: 1950, difficulty: 'survey', detail: 'Cook’s Endeavour voyage ran from 1768 to 1771. It observed the transit of Venus and charted New Zealand and the east coast of Australia for Britain.', source: 'Royal Museums Greenwich — Exploration and discovery guide', sourceUrl: 'https://www.rmg.co.uk/collections/research-guides/research-guide-q1-exploration-discovery', verifiedAt: '2026-08-31' },
];

export function formatHistoryYear(year: number) {
  if (year < 0) return `${Math.abs(year).toLocaleString()} BCE`;
  if (year > 0) return `${year.toLocaleString()} CE`;
  return 'BCE / CE';
}

function hash(value: string) {
  let result = 2166136261;
  for (const character of value) result = Math.imul(result ^ character.charCodeAt(0), 16777619);
  return result >>> 0;
}

export function dailyHistoryDeck(dayKey: string, questions = historyQuestions) {
  return [...questions].sort((left, right) => hash(`${dayKey}:${left.id}`) - hash(`${dayKey}:${right.id}`)).slice(0, Math.min(dailyHistoryQuestionCount, questions.length));
}

export function historyPoints(guess: number, answer: number) {
  const distance = Math.abs(guess - answer);
  if (distance === 0) return 1000;
  if (distance <= 2) return 900;
  if (distance <= 5) return 800;
  if (distance <= 10) return 650;
  if (distance <= 25) return 500;
  if (distance <= 50) return 300;
  if (distance <= 100) return 150;
  return 0;
}

export function historyLevel(scores: number[]) {
  const average = scores.length ? scores.reduce((sum, score) => sum + score, 0) / scores.length : 0;
  if (average >= 900) return { name: 'PhD-level round', note: 'Nearly exact across the whole set.' };
  if (average >= 750) return { name: 'Graduate seminar', note: 'Excellent chronology, including the harder dates.' };
  if (average >= 600) return { name: 'History undergraduate', note: 'Strong command of the broad timeline.' };
  if (average >= 450) return { name: '10th-grade history', note: 'The major eras are in place.' };
  if (average >= 300) return { name: '7th-grade history', note: 'A useful timeline is taking shape.' };
  return { name: '3rd-grade history', note: 'Start with the big anchors and play again tomorrow.' };
}
