export type HistoryQuestion = {
  id: string;
  prompt: string;
  year: number;
  min: number;
  max: number;
  difficulty: 'core' | 'survey' | 'specialist';
  detail: string;
  source: string;
  sourceUrl: string;
  verifiedAt: string;
};

export const historyQuestionTarget = 1000;
export const dailyHistoryQuestionCount = 10;

export const historyQuestions: HistoryQuestion[] = [
  { id: 'djoser-step-pyramid', prompt: 'Around when was Djoser’s Step Pyramid built?', year: -2780, min: -3200, max: -2300, difficulty: 'survey', detail: 'The Smithsonian dates the project to around 2780 BCE and identifies Imhotep as its architect. The exact chronology of Egypt’s Third Dynasty remains approximate.', source: 'Smithsonian Institution — The Egyptian Pyramid', sourceUrl: 'https://www.si.edu/spotlight/ancient-egypt/pyramid', verifiedAt: '2026-08-31' },
  { id: 'code-of-hammurabi', prompt: 'Around when was Hammurabi’s law code carved?', year: -1750, min: -2200, max: -1300, difficulty: 'survey', detail: 'The Louvre dates the surviving stela to Hammurabi’s reign, 1792–1750 BCE. This game uses 1750 BCE as a memorable approximate anchor, not a precise day.', source: 'Musée du Louvre — Code of Hammurabi', sourceUrl: 'https://collections.louvre.fr/en/ark:/53355/cl010174436', verifiedAt: '2026-08-31' },
  { id: 'olmec-florescence', prompt: 'Around when did the Olmec cultural florescence begin?', year: -1200, min: -1600, max: -700, difficulty: 'survey', detail: 'The Met dates the major Olmec cultural and artistic florescence on Mexico’s Gulf Coast to roughly 1200–400 BCE. “Olmec” groups were not a single unified empire.', source: 'Metropolitan Museum of Art — Olmec Art', sourceUrl: 'https://www.metmuseum.org/es/essays/olmec-art', verifiedAt: '2026-08-31' },
  { id: 'achaemenid-empire', prompt: 'Around when did the Achaemenid Persian Empire begin?', year: -550, min: -800, max: -300, difficulty: 'core', detail: 'The Achaemenid Empire is conventionally dated from about 550 BCE, when Cyrus II overthrew the Median king and began a rapid imperial expansion.', source: 'Metropolitan Museum of Art — Achaemenid Persian Empire', sourceUrl: 'https://www.metmuseum.org/ja/essays/the-achaemenid-persian-empire-550-330-b-c', verifiedAt: '2026-08-31' },
  { id: 'mauryan-empire', prompt: 'Around when did the Mauryan Empire begin?', year: -321, min: -550, max: -100, difficulty: 'survey', detail: 'The Mauryan dynasty emerged around 321 BCE and built the first empire to unite most of the Indian subcontinent. Its boundaries changed over time.', source: 'Metropolitan Museum of Art — The Year One', sourceUrl: 'https://resources.metmuseum.org/resources/metpublications/pdf/The_Year_One_Art_of_the_Ancient_World_East_and_West.pdf', verifiedAt: '2026-08-31' },
  { id: 'teotihuacan-established', prompt: 'Around when was Teotihuacan established?', year: -150, min: -400, max: 100, difficulty: 'specialist', detail: 'The Met’s chronology places Teotihuacan’s establishment around 150 BCE. The settlement expanded over generations rather than appearing as a finished city in one year.', source: 'Metropolitan Museum of Art — Mexico, 1000 BCE–1 CE', sourceUrl: 'https://82nd-and-fifth.metmuseum.org/toah/ht/04/cam.html', verifiedAt: '2026-08-31' },
  { id: 'teotihuacan-city-grid', prompt: 'Around when was Teotihuacan’s city grid established?', year: 50, min: -150, max: 300, difficulty: 'specialist', detail: 'The Met dates establishment of Teotihuacan’s grid and early monumental construction along the Street of the Dead to around 50 CE.', source: 'Metropolitan Museum of Art — Mexico, 1–500 CE', sourceUrl: 'https://82nd-and-fifth.metmuseum.org/toah/ht/05/cam.html', verifiedAt: '2026-08-31' },
  { id: 'classic-maya-city-states', prompt: 'Around when did Classic Maya dynastic city-states emerge?', year: 250, min: 1, max: 600, difficulty: 'survey', detail: 'The conventional Classic Maya period begins around 250 CE, when dynastic city-states and their characteristic monuments became prominent. Period boundaries are scholarly tools.', source: 'Metropolitan Museum of Art — Maya Area, 1–500 CE', sourceUrl: 'https://82nd-and-fifth.metmuseum.org/toah/ht/05/caa.html', verifiedAt: '2026-08-31' },
  { id: 'aksumite-coinage', prompt: 'Around when did the kingdom of Aksum begin issuing coins?', year: 270, min: 1, max: 600, difficulty: 'specialist', detail: 'Aksum began minting its own coinage around the late third century CE. The exact opening date is approximate, so the game uses 270 CE as a rough anchor.', source: 'Metropolitan Museum of Art — Foundations of Aksumite Civilization', sourceUrl: 'https://www.metmuseum.org/ja/essays/foundations-of-aksumite-civilization-and-its-christian-legacy-1st-7th-century', verifiedAt: '2026-08-31' },
  { id: 'gupta-dynasty', prompt: 'Around when did the Gupta dynasty begin?', year: 320, min: 100, max: 600, difficulty: 'survey', detail: 'The Gupta era is conventionally dated from around 320 CE. Its political reach and the “golden age” label both require regional and cultural qualification.', source: 'Smarthistory — The Gupta Period', sourceUrl: 'https://smarthistory.org/gupta-period/', verifiedAt: '2026-08-31' },
  { id: 'teotihuacan-tikal', prompt: 'When did a Teotihuacan-linked force arrive at Tikal?', year: 378, min: 150, max: 600, difficulty: 'specialist', detail: 'Maya inscriptions record the arrival of a figure linked to Teotihuacan at Tikal in 378 CE, followed by a new ruler with strong central Mexican ties.', source: 'Metropolitan Museum of Art — Maya Area, 1–500 CE', sourceUrl: 'https://82nd-and-fifth.metmuseum.org/toah/ht/05/caa.html', verifiedAt: '2026-08-31' },
  { id: 'palenque-dynasty', prompt: 'When did Palenque’s recorded dynasty begin?', year: 431, min: 200, max: 700, difficulty: 'specialist', detail: 'Palenque’s inscriptions date the accession of its first recorded dynastic ruler, K’uk’ Balam I, to 431 CE. Earlier settlement at the site is not ruled out.', source: 'Metropolitan Museum of Art — Maya Area, 1–500 CE', sourceUrl: 'https://82nd-and-fifth.metmuseum.org/toah/ht/05/caa.html', verifiedAt: '2026-08-31' },
  { id: 'olympic-chronology', prompt: 'When does the reliable ancient Olympic chronology begin?', year: -776, min: -1100, max: -500, difficulty: 'specialist', detail: 'The conventional reliable list begins with the victor Koroibos in 776 BCE. Games and legends existed earlier, so this is not a claim that Olympic competition began that year.', source: 'Journal of Olympic History — Ancient Olympic Apocrypha', sourceUrl: 'https://library.olympics.com/digitalCollection/DigitalCollectionAttachmentDownloadHandler.ashx?documentId=2435425&parentDocumentId=2435424&skipCopyright=true&skipWatermark=true', verifiedAt: '2026-08-31' },
  { id: 'battle-of-marathon', prompt: 'When was the Battle of Marathon?', year: -490, min: -700, max: -300, difficulty: 'core', detail: 'Athenians and Plataeans defeated a Persian invasion force at Marathon in 490 BCE during the Greco-Persian Wars.', source: 'Encyclopaedia Britannica — Battle of Marathon', sourceUrl: 'https://www.britannica.com/event/Battle-of-Marathon', verifiedAt: '2026-08-31' },
  { id: 'alexander-death', prompt: 'When did Alexander the Great die?', year: -323, min: -500, max: -100, difficulty: 'core', detail: 'Alexander died unexpectedly in Babylon in June 323 BCE. His generals then fought over and divided the empire.', source: 'Metropolitan Museum of Art — The Hellenistic Age', sourceUrl: 'https://www.metmuseum.org/essays/art-of-the-hellenistic-age-and-the-hellenistic-tradition', verifiedAt: '2026-08-31' },
  { id: 'qin-unification', prompt: 'When did Qin unify China?', year: -221, min: -450, max: -50, difficulty: 'survey', detail: 'Ying Zheng conquered the remaining rival states and proclaimed himself First Emperor in 221 BCE. The Qin dynasty itself was short-lived.', source: 'Metropolitan Museum of Art — Age of Empires', sourceUrl: 'https://www.metmuseum.org/exhibitions/listings/2017/age-of-empires/exhibition-galleries', verifiedAt: '2026-08-31' },
  { id: 'augustus-title', prompt: 'When did Octavian receive the title Augustus?', year: -27, min: -150, max: 100, difficulty: 'survey', detail: 'The Roman Senate awarded Octavian the title Augustus in 27 BCE, the conventional beginning of the Roman imperial principate.', source: 'Metropolitan Museum of Art — The Roman Empire', sourceUrl: 'https://www.metmuseum.org/essays/the-roman-empire-27-b-c-393-a-d', verifiedAt: '2026-08-31' },
  { id: 'vesuvius-pompeii', prompt: 'When did Vesuvius bury Pompeii and Herculaneum?', year: 79, min: -100, max: 300, difficulty: 'core', detail: 'Mount Vesuvius erupted in 79 CE, burying Pompeii, Herculaneum, and nearby settlements and preserving an exceptional record of Roman life.', source: 'Metropolitan Museum of Art — Roman Art', sourceUrl: 'https://www.metmuseum.org/met-publications/roman-art-a-resource-for-educators', verifiedAt: '2026-08-31' },
  { id: 'constantinople-capital', prompt: 'When did Constantine establish Constantinople as New Rome?', year: 330, min: 150, max: 550, difficulty: 'survey', detail: 'Constantine dedicated Constantinople in 330 CE and shifted the imperial center eastward. Rome remained central to the western church.', source: 'Metropolitan Museum of Art — Italian Peninsula, 1–500 CE', sourceUrl: 'https://www.metmuseum.org/toah/ht/05/eust.html', verifiedAt: '2026-08-31' },
  { id: 'western-rome-end', prompt: 'When was the last western Roman emperor deposed?', year: 476, min: 250, max: 700, difficulty: 'core', detail: 'Odovacer deposed Romulus Augustulus in 476 CE, the conventional endpoint of the Western Roman Empire. The Eastern Roman Empire continued for centuries.', source: 'Metropolitan Museum of Art — The Roman Empire', sourceUrl: 'https://www.metmuseum.org/essays/the-roman-empire-27-b-c-393-a-d', verifiedAt: '2026-08-31' },
  { id: 'tang-dynasty', prompt: 'When did the Tang dynasty begin in China?', year: 618, min: 450, max: 850, difficulty: 'survey', detail: 'Li Yuan founded the Tang dynasty in 618 CE. Tang rule lasted, with an interruption, until 907 and presided over a major era of trade and cultural exchange.', source: 'Metropolitan Museum of Art — Central and North Asia, 500–1000', sourceUrl: 'https://82nd-and-fifth.metmuseum.org/toah/ht/06/nc.html', verifiedAt: '2026-08-31' },
  { id: 'hijra', prompt: 'When did Muhammad and his followers migrate to Medina?', year: 622, min: 450, max: 850, difficulty: 'core', detail: 'The Hijra from Mecca to Medina occurred in 622 CE. It marks the starting point of the Islamic calendar, not the beginning of Muhammad’s prophetic career.', source: 'Metropolitan Museum of Art — The Birth of Islam', sourceUrl: 'https://www.metmuseum.org/essays/the-birth-of-islam', verifiedAt: '2026-08-31' },
  { id: 'baghdad-founded', prompt: 'When did the Abbasids found Baghdad?', year: 762, min: 550, max: 1000, difficulty: 'survey', detail: 'The Abbasid caliph al-Mansur founded Baghdad as his new capital in 762 CE. The city became a major political, commercial, and intellectual center.', source: 'Metropolitan Museum of Art — Central and North Asia, 500–1000', sourceUrl: 'https://82nd-and-fifth.metmuseum.org/toah/ht/06/nc.html', verifiedAt: '2026-08-31' },
  { id: 'charlemagne-emperor', prompt: 'When was Charlemagne crowned emperor in Rome?', year: 800, min: 600, max: 1050, difficulty: 'core', detail: 'Pope Leo III crowned Charlemagne emperor in Rome on Christmas Day in 800 CE. The title shaped later claims to imperial authority in western Europe.', source: 'Metropolitan Museum of Art — Carolingian Art', sourceUrl: 'https://www.metmuseum.org/essays/carolingian-art', verifiedAt: '2026-08-31' },
  { id: 'norman-conquest', prompt: 'When did the Norman Conquest of England begin?', year: 1066, min: 850, max: 1250, difficulty: 'core', detail: 'William of Normandy invaded England and defeated Harold at Hastings in 1066. Conquest and consolidation continued after the battle.', source: 'UK Parliament — The Palace and the Normans', sourceUrl: 'https://www.parliament.uk/about/living-heritage/building/palace/estatehistory/the-middle-ages/palace-normans/', verifiedAt: '2026-08-31' },
  { id: 'first-crusade', prompt: 'When did Pope Urban II call the First Crusade?', year: 1095, min: 850, max: 1300, difficulty: 'survey', detail: 'Urban II called for an armed pilgrimage at the Council of Clermont in 1095. Crusading armies reached and captured Jerusalem in 1099.', source: 'Metropolitan Museum of Art — The Crusades', sourceUrl: 'https://www.metmuseum.org/toah/hd/crus/hd_crus.htm', verifiedAt: '2026-08-31' },
  { id: 'genghis-khan-proclaimed', prompt: 'When was Temüjin proclaimed Genghis Khan?', year: 1206, min: 950, max: 1400, difficulty: 'survey', detail: 'A great assembly recognized Temüjin as Genghis Khan in 1206, conventionally marking the foundation of the Mongol Empire.', source: 'Metropolitan Museum of Art — The Legacy of Genghis Khan', sourceUrl: 'https://www.metmuseum.org/essays/the-legacy-of-genghis-khan', verifiedAt: '2026-08-31' },
  { id: 'mali-empire-rise', prompt: 'Around when did the Mali Empire emerge?', year: 1235, min: 950, max: 1500, difficulty: 'specialist', detail: 'Mali’s rise is conventionally associated with Sundiata’s victory around 1235. The date is approximate and partly reconstructed from oral traditions.', source: 'Metropolitan Museum of Art — Empires of the Western Sudan', sourceUrl: 'https://www.metmuseum.org/essays/the-empires-of-the-western-sudan', verifiedAt: '2026-08-31' },
  { id: 'black-death-europe', prompt: 'When did the Black Death reach Europe?', year: 1347, min: 1150, max: 1550, difficulty: 'core', detail: 'The pandemic reached Mediterranean Europe in 1347 and spread widely through 1351. Outbreaks and demographic effects varied across regions.', source: 'Metropolitan Museum of Art — The Art of Renaissance Europe', sourceUrl: 'https://www.metmuseum.org/-/media/files/learn/for-educators/publications-for-educators/renaissance.pdf', verifiedAt: '2026-08-31' },
  { id: 'fall-of-constantinople', prompt: 'When did the Ottomans capture Constantinople?', year: 1453, min: 1250, max: 1650, difficulty: 'core', detail: 'Mehmed II’s Ottoman army captured Constantinople in May 1453, ending the Byzantine Empire. Trebizond remained independent until 1461.', source: 'Metropolitan Museum of Art — The Art of Renaissance Europe', sourceUrl: 'https://www.metmuseum.org/-/media/files/learn/for-educators/publications-for-educators/renaissance.pdf', verifiedAt: '2026-08-31' },
  { id: 'magna-carta', prompt: 'When was Magna Carta first issued?', year: 1215, min: 1000, max: 1500, difficulty: 'core', detail: 'King John authorized the first Magna Carta at Runnymede in June 1215. Later reissues changed its text and legacy.', source: 'UK Parliament — Magna Carta', sourceUrl: 'https://www.parliament.uk/about/living-heritage/evolutionofparliament/originsofparliament/birthofparliament/overview/magnacarta/', verifiedAt: '2026-08-31' },
  { id: 'ming-dynasty', prompt: 'When did Zhu Yuanzhang establish the Ming dynasty?', year: 1368, min: 1150, max: 1550, difficulty: 'survey', detail: 'Zhu Yuanzhang emerged victorious in 1368, expelled the Yuan court, and ruled as the Hongwu emperor.', source: 'Metropolitan Museum of Art — The Yuan Revolution', sourceUrl: 'https://www.metmuseum.org/exhibitions/listings/2010/yuan-revolution', verifiedAt: '2026-08-31' },
  { id: 'gutenberg-printing', prompt: 'Around when did Gutenberg-era movable-type printing begin in Europe?', year: 1450, min: 1250, max: 1650, difficulty: 'core', detail: 'The date is approximate: historians place the beginning of European typography around 1450, before the Gutenberg Bible was completed.', source: 'Library of Congress — Gutenberg resources', sourceUrl: 'https://guides.loc.gov/gutenberg/resources', verifiedAt: '2026-08-31' },
  { id: 'columbus-caribbean', prompt: 'When did Columbus first reach the Caribbean?', year: 1492, min: 1300, max: 1700, difficulty: 'core', detail: 'Columbus reached the Bahamian island Guanahaní on 12 October 1492, beginning a new phase of European conquest and colonization.', source: 'Library of Congress — Columbus and the Taíno', sourceUrl: 'https://www.loc.gov/exhibits/exploring-the-early-americas/columbus-and-the-taino.html', verifiedAt: '2026-08-31' },
  { id: 'qing-dynasty', prompt: 'When did the Manchus establish Qing rule in China?', year: 1644, min: 1450, max: 1800, difficulty: 'survey', detail: 'The Manchus entered Beijing and established Qing rule in 1644; conquest and consolidation continued for decades.', source: 'Metropolitan Museum of Art — The Qing Dynasty', sourceUrl: 'https://www.metmuseum.org/essays/the-qing-dynasty-1644-1911-painting', verifiedAt: '2026-08-31' },
  { id: 'spinning-jenny', prompt: 'When did James Hargreaves invent the spinning jenny?', year: 1764, min: 1600, max: 1900, difficulty: 'survey', detail: 'Hargreaves is generally credited with inventing the multi-spindle spinning jenny around 1764; he patented a later version in 1770.', source: 'Encyclopaedia Britannica — Spinning jenny', sourceUrl: 'https://www.britannica.com/technology/spinning-jenny', verifiedAt: '2026-08-31' },
  { id: 'watt-patent', prompt: 'When was Watt’s separate-condenser patent granted?', year: 1769, min: 1600, max: 1900, difficulty: 'survey', detail: 'Watt conceived the separate condenser earlier, but this question asks for the patent granted on 5 January 1769.', source: 'Science Museum — James Watt and the separate condenser', sourceUrl: 'https://blog.sciencemuseum.org.uk/james-watt-and-the-separate-condenser/', verifiedAt: '2026-08-31' },
  { id: 'french-revolution', prompt: 'When did the French Revolution begin?', year: 1789, min: 1650, max: 1950, difficulty: 'core', detail: 'This uses 1789, the year of the Estates-General, the National Assembly, and the storming of the Bastille, as the conventional start.', source: 'U.S. National Archives — Onset of the French Revolution', sourceUrl: 'https://www.archives.gov/exhibits/eyewitness/html.php?section=1', verifiedAt: '2026-08-31' },
  { id: 'haitian-independence', prompt: 'When did Haiti declare independence from France?', year: 1804, min: 1650, max: 1950, difficulty: 'survey', detail: 'Haitian generals signed the declaration on 1 January 1804 after a thirteen-year revolution against slavery and colonial rule.', source: 'Library of Congress — Ayiti Reimagined', sourceUrl: 'https://guides.loc.gov/haiti-reimagined', verifiedAt: '2026-08-31' },
  { id: 'telegraph', prompt: 'When was a practical electric telegraph first demonstrated in Britain?', year: 1837, min: 1700, max: 2000, difficulty: 'specialist', detail: 'Cooke and Wheatstone demonstrated their five-needle electric telegraph to railway directors in 1837.', source: 'Science Museum — Cooke and Wheatstone telegraph', sourceUrl: 'https://blog.sciencemuseum.org.uk/revealing-the-real-cooke-and-wheatstone-telegraph-dial/', verifiedAt: '2026-08-31' },
  { id: 'meiji-restoration', prompt: 'When did the Meiji Restoration change Japan’s regime?', year: 1868, min: 1700, max: 2000, difficulty: 'survey', detail: 'Imperial rule was proclaimed in January 1868, beginning the new Meiji government and a far-reaching transformation of Japan.', source: 'National Diet Library of Japan — Meiji government', sourceUrl: 'https://www.ndl.go.jp/portrait/e/pickup/012/', verifiedAt: '2026-08-31' },
  { id: 'indian-independence', prompt: 'When did British rule end in India?', year: 1947, min: 1800, max: 2020, difficulty: 'core', detail: 'British India was partitioned into India and Pakistan in August 1947; independence and partition unfolded together.', source: 'UK National Archives — Indian Independence', sourceUrl: 'https://www.nationalarchives.gov.uk/education/resources/indian-independence/', verifiedAt: '2026-08-31' },
  { id: 'berlin-wall-fall', prompt: 'When did the Berlin Wall fall?', year: 1989, min: 1900, max: 2020, difficulty: 'core', detail: 'East Germany opened the border on 9 November 1989. Formal German reunification followed in October 1990.', source: 'German Bundestag — 1989–1990', sourceUrl: 'https://www.bundestag.de/resource/blob/480634/exhibition_dome.pdf', verifiedAt: '2026-08-31' },
];

export function formatHistoryYear(year: number) {
  if (year < 0) return `${Math.abs(year).toLocaleString()} BCE`;
  if (year > 0) return `${year.toLocaleString()} CE`;
  return 'BCE / CE';
}

function hash(value: string) {
  let result = 2166136261;
  for (const character of value) result = Math.imul(result ^ character.charCodeAt(0), 16777619);
  return result >>> 0;
}

export function dailyHistoryDeck(dayKey: string, questions = historyQuestions) {
  return [...questions].sort((left, right) => hash(`${dayKey}:${left.id}`) - hash(`${dayKey}:${right.id}`)).slice(0, Math.min(dailyHistoryQuestionCount, questions.length));
}

export function historyPoints(guess: number, answer: number) {
  const distance = Math.abs(guess - answer);
  if (distance === 0) return 1000;
  if (distance <= 2) return 900;
  if (distance <= 5) return 800;
  if (distance <= 10) return 650;
  if (distance <= 25) return 500;
  if (distance <= 50) return 300;
  if (distance <= 100) return 150;
  return 0;
}

export function historyLevel(scores: number[]) {
  const average = scores.length ? scores.reduce((sum, score) => sum + score, 0) / scores.length : 0;
  if (average >= 900) return { name: 'PhD-level round', note: 'Nearly exact across the whole set.' };
  if (average >= 750) return { name: 'Graduate seminar', note: 'Excellent chronology, including the harder dates.' };
  if (average >= 600) return { name: 'History undergraduate', note: 'Strong command of the broad timeline.' };
  if (average >= 450) return { name: '10th-grade history', note: 'The major eras are in place.' };
  if (average >= 300) return { name: '7th-grade history', note: 'A useful timeline is taking shape.' };
  return { name: '3rd-grade history', note: 'Start with the big anchors and play again tomorrow.' };
}
